version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  tdengine:
    image: zitsen/tdengine-server:2.1.2.0
    environment: 
      TAOS_FQDN: "tdengine"
  producer:
    image: zitsen/tdengine-client:2.1.2.0
    volumes:
      - "./producer:/usr/bin/producer"
    command:
      - "/usr/bin/producer"
  consumer:
    image: zitsen/tdengine-client:2.1.2.0
    volumes:
      - "./consumer:/usr/bin/consumer"
    command:
      - "/usr/bin/consumer"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
