version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  tdengine:
    image: zitsen/tdengine-server:2.1.2.0
    environment: 
      TAOS_FQDN: "tdengine"
  producer:
    image: zitsen/tdengine-client:2.1.2.0
    volumes:
      - "./producer:/usr/bin/producer"
    command:
      - "/usr/bin/producer"
  consumer:
    image: zitsen/tdengine-client:2.1.2.0
    volumes:
      - "./consumer:/usr/bin/consumer"
    environment: 
      - KAFKA_BROKERS=kafka:9092
    command:
      - "/usr/bin/consumer"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
